services:
  - type: web
    name: pledgeit-backend
    env: python
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn backend.main:app --reload"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10

  - type: web
    name: pledgeit-frontend
    env: node
    plan: free
    buildCommand: "cd frontend && npm install && npm run build"
    startCommand: "npm install -g serve && serve -s frontend/dist"
    envVars:
      - key: NODE_VERSION
        value: 18